<?php

$statusOptions = ['active' => 'Active', 'inactive' => 'Inactive'];
$paymentModes = ['cash' => 'Cash', 'upi' => 'UPI', 'bank' => 'Bank Transfer', 'card' => 'Card', 'cheque' => 'Cheque'];
$bloodGroups = ['a_positive' => 'A+', 'a_negative' => 'A-', 'b_positive' => 'B+', 'b_negative' => 'B-', 'ab_positive' => 'AB+', 'ab_negative' => 'AB-', 'o_positive' => 'O+', 'o_negative' => 'O-'];
$weekDays = ['monday' => 'Monday', 'tuesday' => 'Tuesday', 'wednesday' => 'Wednesday', 'thursday' => 'Thursday', 'friday' => 'Friday', 'saturday' => 'Saturday', 'sunday' => 'Sunday'];
$expenseTypes = ['general' => 'General', 'electricity' => 'Electricity', 'water' => 'Water', 'maintenance' => 'Maintenance', 'repair' => 'Repair', 'food' => 'Food', 'cleaning' => 'Cleaning', 'rent' => 'Rent', 'staff' => 'Staff', 'student' => 'Student', 'other' => 'Other'];

return [
    'modules' => [
        'branches' => [
            'title' => 'Hostel Branches',
            'singular' => 'Hostel Branch',
            'icon' => 'fas fa-code-branch',
            'menu' => 'Settings',
            'table' => 'hostel_branches',
            'quick' => ['name', 'code', 'status'],
            'fields' => [
                'name' => ['label' => 'Branch Name', 'type' => 'text', 'required' => true],
                'code' => ['label' => 'Branch Code', 'type' => 'text', 'nullable' => true, 'unique' => true],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => $statusOptions, 'default' => 'active'],
            ],
        ],
        'students' => [
            'title' => 'Students',
            'singular' => 'Student',
            'icon' => 'fas fa-user-graduate',
            'menu' => 'Operations',
            'table' => 'hostel_students',
            'quick' => ['registration_no', 'name', 'mobile', 'branch_id', 'room_id', 'status'],
            'fields' => [
                'user_id' => ['label' => 'Login User', 'type' => 'select', 'source' => 'users', 'nullable' => true],
                'default_password' => ['label' => 'Default Password', 'type' => 'password', 'nullable' => true],
                'branch_id' => ['label' => 'Hostel Branch', 'type' => 'select', 'source' => 'branches', 'nullable' => true],
                'room_id' => ['label' => 'Room / Area', 'type' => 'select', 'source' => 'rooms', 'nullable' => true, 'depends_on' => 'branch_id'],
                'photo' => ['label' => 'Student Photo', 'type' => 'file', 'nullable' => true],
                'registration_no' => ['label' => 'Registration No', 'type' => 'text', 'required' => true, 'unique' => true],
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'mobile' => ['label' => 'Mobile', 'type' => 'text', 'required' => true],
                'alternate_mobile' => ['label' => 'Alternate Mobile', 'type' => 'text', 'nullable' => true],
                'email' => ['label' => 'Email', 'type' => 'email', 'nullable' => true],
                'dob' => ['label' => 'Date of Birth', 'type' => 'date', 'nullable' => true],
                'blood_group' => ['label' => 'Blood Group', 'type' => 'select', 'options' => $bloodGroups, 'nullable' => true],
                'aadhaar_number' => ['label' => 'Aadhaar Number', 'type' => 'text', 'nullable' => true],
                'institute_name' => ['label' => 'Institute Name', 'type' => 'text', 'nullable' => true],
                'batch' => ['label' => 'Batch', 'type' => 'text', 'nullable' => true],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'nullable' => true],
                'guardian_name' => ['label' => 'Guardian Name', 'type' => 'text', 'nullable' => true],
                'guardian_mobile' => ['label' => 'Guardian Mobile', 'type' => 'text', 'nullable' => true],
                'course' => ['label' => 'Course / Class', 'type' => 'text', 'nullable' => true],
                'joining_date' => ['label' => 'Joining Date', 'type' => 'date', 'nullable' => true],
                'aadhaar_front' => ['label' => 'Aadhaar Front Image', 'type' => 'file', 'nullable' => true],
                'aadhaar_back' => ['label' => 'Aadhaar Back Image', 'type' => 'file', 'nullable' => true],
                'id_card_front' => ['label' => 'ID Card Front Image', 'type' => 'file', 'nullable' => true],
                'id_card_back' => ['label' => 'ID Card Back Image', 'type' => 'file', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => $statusOptions, 'default' => 'active'],
            ],
        ],
        'rooms' => [
            'title' => 'Rooms',
            'singular' => 'Room',
            'icon' => 'fas fa-door-open',
            'menu' => 'Operations',
            'table' => 'hostel_rooms',
            'quick' => ['branch_id', 'room_number', 'floor_number', 'room_type', 'total_beds', 'status'],
            'fields' => [
                'branch_id' => ['label' => 'Hostel Branch', 'type' => 'select', 'source' => 'branches', 'nullable' => true],
                'room_number' => ['label' => 'Room Number', 'type' => 'text', 'required' => true],
                'floor_number' => ['label' => 'Floor Number', 'type' => 'text', 'nullable' => true],
                'room_type' => ['label' => 'Room Type', 'type' => 'select', 'options' => ['single' => 'Single', 'double' => 'Double', 'triple' => 'Triple', 'dormitory' => 'Dormitory']],
                'total_beds' => ['label' => 'Total Beds', 'type' => 'number', 'default' => 1],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['available' => 'Available', 'occupied' => 'Occupied', 'maintenance' => 'Maintenance'], 'default' => 'available'],
            ],
        ],
        'beds' => [
            'title' => 'Beds',
            'singular' => 'Bed',
            'icon' => 'fas fa-bed',
            'menu' => 'Operations',
            'table' => 'hostel_beds',
            'quick' => ['room_id', 'bed_number', 'status'],
            'fields' => [
                'room_id' => ['label' => 'Room', 'type' => 'select', 'source' => 'rooms', 'required' => true],
                'bed_number' => ['label' => 'Bed Number', 'type' => 'text', 'required' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['vacant' => 'Vacant', 'occupied' => 'Occupied', 'repair' => 'Repair'], 'default' => 'vacant'],
            ],
        ],
        'room-allocations' => [
            'title' => 'Room Allocations',
            'singular' => 'Room Allocation',
            'icon' => 'fas fa-people-arrows',
            'menu' => 'Operations',
            'table' => 'hostel_room_allocations',
            'quick' => ['student_id', 'branch_id', 'room_id', 'allocation_date', 'shift_date', 'status'],
            'fields' => [
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'required' => true],
                'branch_id' => ['label' => 'Hostel Branch', 'type' => 'select', 'source' => 'branches', 'nullable' => true],
                'room_id' => ['label' => 'Room / Area', 'type' => 'select', 'source' => 'rooms', 'required' => true, 'depends_on' => 'branch_id'],
                'bed_id' => ['label' => 'Bed', 'type' => 'select', 'source' => 'beds', 'nullable' => true, 'depends_on' => 'room_id'],
                'allocation_date' => ['label' => 'Allocation Date', 'type' => 'date', 'nullable' => true],
                'shift_date' => ['label' => 'Shift Date', 'type' => 'date', 'nullable' => true],
                'vacate_date' => ['label' => 'Vacate Date', 'type' => 'date', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['active' => 'Active', 'vacated' => 'Vacated', 'changed' => 'Changed'], 'default' => 'active'],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'accessories' => [
            'title' => 'Accessories',
            'singular' => 'Accessory',
            'icon' => 'fas fa-chair',
            'menu' => 'Operations',
            'table' => 'hostel_accessories',
            'quick' => ['branch_id', 'room_id', 'name', 'quantity', 'status'],
            'fields' => [
                'branch_id' => ['label' => 'Hostel Branch', 'type' => 'select', 'source' => 'branches', 'nullable' => true],
                'room_id' => ['label' => 'Room', 'type' => 'select', 'source' => 'rooms', 'required' => true, 'depends_on' => 'branch_id'],
                'name' => ['label' => 'Accessory Name', 'type' => 'text', 'required' => true],
                'quantity' => ['label' => 'Quantity', 'type' => 'number', 'default' => 1],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['good' => 'Good', 'damaged' => 'Damaged', 'repair' => 'Repair', 'replaced' => 'Replaced'], 'default' => 'good'],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'student-attendance' => [
            'title' => 'Student Attendance',
            'singular' => 'Student Attendance',
            'icon' => 'fas fa-user-check',
            'menu' => 'Daily Work',
            'table' => 'hostel_student_attendance',
            'quick' => ['student_id', 'attendance_date', 'status', 'punch_in_time', 'punch_out_time', 'image'],
            'fields' => [
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'required' => true],
                'attendance_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['present' => 'Present', 'absent' => 'Absent'], 'default' => 'present'],
                'punch_in_time' => ['label' => 'Punch In Time', 'type' => 'time', 'nullable' => true],
                'punch_out_time' => ['label' => 'Punch Out Time', 'type' => 'time', 'nullable' => true],
                'attendance_datetime' => ['label' => 'Date & Time', 'type' => 'datetime', 'nullable' => true],
                'image' => ['label' => 'Attendance Image', 'type' => 'file', 'nullable' => true],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'staff-attendance' => [
            'title' => 'Staff Attendance',
            'singular' => 'Staff Attendance',
            'icon' => 'fas fa-clipboard-check',
            'menu' => 'Daily Work',
            'table' => 'hostel_staff_attendance',
            'quick' => ['staff_id', 'attendance_date', 'status'],
            'fields' => [
                'staff_id' => ['label' => 'Staff', 'type' => 'select', 'source' => 'staff', 'required' => true],
                'attendance_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['present' => 'Present', 'absent' => 'Absent', 'leave' => 'Leave'], 'default' => 'present'],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'visitors' => [
            'title' => 'Visitors',
            'singular' => 'Visitor',
            'icon' => 'fas fa-address-book',
            'menu' => 'Daily Work',
            'table' => 'hostel_visitors',
            'quick' => ['name', 'mobile', 'student_id', 'in_time', 'out_time'],
            'fields' => [
                'name' => ['label' => 'Visitor Name', 'type' => 'text', 'required' => true],
                'mobile' => ['label' => 'Mobile', 'type' => 'text', 'nullable' => true],
                'relation' => ['label' => 'Relation', 'type' => 'text', 'nullable' => true],
                'purpose' => ['label' => 'Purpose', 'type' => 'textarea', 'nullable' => true],
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'nullable' => true],
                'room_id' => ['label' => 'Room', 'type' => 'select', 'source' => 'rooms', 'nullable' => true],
                'visit_date' => ['label' => 'Visit Date', 'type' => 'date', 'nullable' => true],
                'in_time' => ['label' => 'In Time', 'type' => 'time', 'nullable' => true],
                'out_time' => ['label' => 'Out Time', 'type' => 'time', 'nullable' => true],
                'id_proof' => ['label' => 'ID Proof Details', 'type' => 'text', 'nullable' => true],
            ],
        ],
        'fees' => [
            'title' => 'Fee Setups',
            'singular' => 'Fee Setup',
            'icon' => 'fas fa-file-invoice-dollar',
            'menu' => 'Finance',
            'table' => 'hostel_fees',
            'quick' => ['student_id', 'monthly_fee', 'admission_fee', 'security_deposit', 'status'],
            'fields' => [
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'required' => true],
                'monthly_fee' => ['label' => 'Monthly Fee', 'type' => 'number', 'default' => 0],
                'admission_fee' => ['label' => 'Admission Fee', 'type' => 'number', 'default' => 0],
                'security_deposit' => ['label' => 'Security Deposit', 'type' => 'number', 'default' => 0],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => $statusOptions, 'default' => 'active'],
            ],
        ],
        'fee-payments' => [
            'title' => 'Fee Payments',
            'singular' => 'Fee Payment',
            'icon' => 'fas fa-receipt',
            'menu' => 'Finance',
            'table' => 'hostel_fee_payments',
            'quick' => ['student_id', 'receipt_number', 'paid_amount', 'due_amount', 'payment_date'],
            'fields' => [
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'required' => true],
                'receipt_number' => ['label' => 'Receipt Number', 'type' => 'text', 'nullable' => true],
                'month' => ['label' => 'Fee Month', 'type' => 'text', 'nullable' => true],
                'paid_amount' => ['label' => 'Paid Amount', 'type' => 'number', 'default' => 0],
                'due_amount' => ['label' => 'Due Amount', 'type' => 'number', 'default' => 0],
                'payment_date' => ['label' => 'Payment Date', 'type' => 'date', 'nullable' => true],
                'payment_mode' => ['label' => 'Payment Mode', 'type' => 'select', 'options' => $paymentModes],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'complaints' => [
            'title' => 'Complaints',
            'singular' => 'Complaint',
            'icon' => 'fas fa-tools',
            'menu' => 'Daily Work',
            'table' => 'hostel_complaints',
            'quick' => ['title', 'category', 'student_id', 'room_id', 'status'],
            'fields' => [
                'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
                'category' => ['label' => 'Category', 'type' => 'text', 'nullable' => true],
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'nullable' => true],
                'room_id' => ['label' => 'Room', 'type' => 'select', 'source' => 'rooms', 'nullable' => true],
                'complaint_date' => ['label' => 'Complaint Date', 'type' => 'date', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['pending' => 'Pending', 'in_progress' => 'In Progress', 'resolved' => 'Resolved'], 'default' => 'pending'],
                'resolution_remark' => ['label' => 'Resolution Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'leaves' => [
            'title' => 'Leaves',
            'singular' => 'Leave',
            'icon' => 'fas fa-calendar-minus',
            'menu' => 'Daily Work',
            'table' => 'hostel_leaves',
            'quick' => ['person_type', 'student_id', 'staff_id', 'from_date', 'status'],
            'fields' => [
                'person_type' => ['label' => 'Person Type', 'type' => 'select', 'options' => ['student' => 'Student', 'staff' => 'Staff'], 'default' => 'student'],
                'student_id' => ['label' => 'Student', 'type' => 'select', 'source' => 'students', 'nullable' => true],
                'staff_id' => ['label' => 'Staff', 'type' => 'select', 'source' => 'staff', 'nullable' => true],
                'leave_type' => ['label' => 'Leave Type', 'type' => 'text', 'nullable' => true],
                'from_date' => ['label' => 'From Date', 'type' => 'date', 'required' => true],
                'to_date' => ['label' => 'To Date', 'type' => 'date', 'required' => true],
                'reason' => ['label' => 'Reason', 'type' => 'textarea', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected'], 'default' => 'pending'],
            ],
        ],
        'staff' => [
            'title' => 'Staff',
            'singular' => 'Staff',
            'icon' => 'fas fa-user-tie',
            'menu' => 'Staff',
            'table' => 'hostel_staff',
            'quick' => ['name', 'mobile', 'designation', 'salary', 'status'],
            'fields' => [
                'user_id' => ['label' => 'Login User', 'type' => 'select', 'source' => 'users', 'nullable' => true],
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'mobile' => ['label' => 'Mobile', 'type' => 'text', 'required' => true],
                'email' => ['label' => 'Email', 'type' => 'email', 'nullable' => true],
                'designation' => ['label' => 'Designation', 'type' => 'text', 'nullable' => true],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'nullable' => true],
                'joining_date' => ['label' => 'Joining Date', 'type' => 'date', 'nullable' => true],
                'salary' => ['label' => 'Salary', 'type' => 'number', 'default' => 0],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => $statusOptions, 'default' => 'active'],
            ],
        ],
        'food-menus' => [
            'title' => 'Food Menus',
            'singular' => 'Food Menu',
            'icon' => 'fas fa-utensils',
            'menu' => 'Operations',
            'table' => 'hostel_food_menus',
            'quick' => ['day', 'morning_snacks', 'breakfast', 'lunch', 'evening_snacks', 'dinner'],
            'fields' => [
                'menu_date' => ['label' => 'Menu Date', 'type' => 'date', 'nullable' => true],
                'day' => ['label' => 'Day', 'type' => 'select', 'options' => $weekDays, 'required' => true, 'unique' => true],
                'day_name' => ['label' => 'Old Day Name', 'type' => 'select', 'options' => $weekDays, 'nullable' => true],
                'morning_snacks' => ['label' => 'Morning Snacks', 'type' => 'textarea', 'nullable' => true],
                'breakfast' => ['label' => 'Breakfast', 'type' => 'textarea', 'nullable' => true],
                'lunch' => ['label' => 'Lunch', 'type' => 'textarea', 'nullable' => true],
                'evening_snacks' => ['label' => 'Evening Snacks', 'type' => 'textarea', 'nullable' => true],
                'dinner' => ['label' => 'Dinner', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'staff-payments' => [
            'title' => 'Staff Payments',
            'singular' => 'Staff Payment',
            'icon' => 'fas fa-money-check-alt',
            'menu' => 'Staff',
            'table' => 'hostel_staff_payments',
            'quick' => ['staff_id', 'staff_attendance_id', 'attendance_days', 'present_days', 'paid_amount', 'payment_date'],
            'fields' => [
                'staff_id' => ['label' => 'Staff', 'type' => 'select', 'source' => 'staff', 'required' => true],
                'staff_attendance_id' => ['label' => 'Staff Attendance', 'type' => 'select', 'source' => 'staff-attendance', 'nullable' => true],
                'attendance_days' => ['label' => 'Attendance Days', 'type' => 'number', 'default' => 0],
                'present_days' => ['label' => 'Present Days', 'type' => 'number', 'default' => 0],
                'salary_month' => ['label' => 'Salary Month', 'type' => 'text', 'nullable' => true],
                'paid_amount' => ['label' => 'Paid Amount', 'type' => 'number', 'default' => 0],
                'due_amount' => ['label' => 'Due Amount', 'type' => 'number', 'default' => 0],
                'payment_mode' => ['label' => 'Payment Mode', 'type' => 'select', 'options' => $paymentModes],
                'payment_date' => ['label' => 'Payment Date', 'type' => 'date', 'nullable' => true],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'staff-works' => [
            'title' => 'Staff Work',
            'singular' => 'Staff Work',
            'icon' => 'fas fa-tasks',
            'menu' => 'Staff',
            'table' => 'hostel_staff_works',
            'quick' => ['staff_id', 'title', 'assigned_date', 'completion_date', 'status'],
            'fields' => [
                'staff_id' => ['label' => 'Staff', 'type' => 'select', 'source' => 'staff', 'required' => true],
                'title' => ['label' => 'Work Title', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'nullable' => true],
                'assigned_date' => ['label' => 'Assigned Date', 'type' => 'date', 'nullable' => true],
                'completion_date' => ['label' => 'Completion Date', 'type' => 'date', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['pending' => 'Pending', 'working' => 'Working', 'completed' => 'Completed'], 'default' => 'pending'],
            ],
        ],
        'expenses' => [
            'title' => 'Expenses',
            'singular' => 'Expense',
            'icon' => 'fas fa-wallet',
            'menu' => 'Finance',
            'table' => 'hostel_expenses',
            'quick' => ['branch_id', 'expense_type', 'title', 'amount', 'expense_date', 'payment_mode'],
            'fields' => [
                'branch_id' => ['label' => 'Hostel Branch', 'type' => 'select', 'source' => 'branches', 'nullable' => true],
                'expense_type' => ['label' => 'Expense Type', 'type' => 'select', 'options' => $expenseTypes, 'default' => 'general'],
                'title' => ['label' => 'Expense Title', 'type' => 'text', 'nullable' => true],
                'category' => ['label' => 'Category', 'type' => 'text', 'nullable' => true],
                'amount' => ['label' => 'Amount', 'type' => 'number', 'default' => 0],
                'expense_date' => ['label' => 'Expense Date', 'type' => 'date', 'nullable' => true],
                'payment_mode' => ['label' => 'Payment Mode', 'type' => 'select', 'options' => $paymentModes],
                'bill_upload' => ['label' => 'Bill Upload', 'type' => 'file', 'nullable' => true],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['paid' => 'Paid', 'unpaid' => 'Unpaid', 'pending' => 'Pending'], 'default' => 'paid'],
            ],
        ],
        'incomes' => [
            'title' => 'Income',
            'singular' => 'Income',
            'icon' => 'fas fa-hand-holding-usd',
            'menu' => 'Finance',
            'table' => 'hostel_incomes',
            'quick' => ['source', 'amount', 'income_date', 'payment_mode'],
            'fields' => [
                'source' => ['label' => 'Income Source', 'type' => 'text', 'required' => true],
                'amount' => ['label' => 'Amount', 'type' => 'number', 'default' => 0],
                'income_date' => ['label' => 'Income Date', 'type' => 'date', 'nullable' => true],
                'payment_mode' => ['label' => 'Payment Mode', 'type' => 'select', 'options' => $paymentModes],
                'remark' => ['label' => 'Remark', 'type' => 'textarea', 'nullable' => true],
            ],
        ],
        'bills' => [
            'title' => 'Bills',
            'singular' => 'Bill',
            'icon' => 'fas fa-file-invoice',
            'menu' => 'Finance',
            'table' => 'hostel_bills',
            'quick' => ['bill_type', 'bill_number', 'bill_date', 'amount', 'payment_status'],
            'fields' => [
                'bill_type' => ['label' => 'Bill Type', 'type' => 'text', 'required' => true],
                'bill_number' => ['label' => 'Bill Number', 'type' => 'text', 'nullable' => true],
                'bill_date' => ['label' => 'Bill Date', 'type' => 'date', 'nullable' => true],
                'amount' => ['label' => 'Amount', 'type' => 'number', 'default' => 0],
                'bill_file' => ['label' => 'Bill Image / PDF', 'type' => 'file', 'nullable' => true],
                'payment_status' => ['label' => 'Payment Status', 'type' => 'select', 'options' => ['paid' => 'Paid', 'unpaid' => 'Unpaid'], 'default' => 'unpaid'],
            ],
        ],
        'notices' => [
            'title' => 'Notices',
            'singular' => 'Notice',
            'icon' => 'fas fa-bullhorn',
            'menu' => 'Content',
            'table' => 'hostel_notices',
            'quick' => ['title', 'notice_date', 'audience', 'status'],
            'fields' => [
                'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'nullable' => true],
                'notice_date' => ['label' => 'Notice Date', 'type' => 'date', 'nullable' => true],
                'audience' => ['label' => 'Audience', 'type' => 'select', 'options' => ['student' => 'Student', 'staff' => 'Staff', 'all' => 'All'], 'default' => 'all'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['published' => 'Published', 'unpublished' => 'Unpublished'], 'default' => 'published'],
            ],
        ],
        'events' => [
            'title' => 'Events',
            'singular' => 'Event',
            'icon' => 'fas fa-calendar-alt',
            'menu' => 'Content',
            'table' => 'hostel_events',
            'quick' => ['title', 'event_date', 'event_time', 'location', 'status'],
            'fields' => [
                'title' => ['label' => 'Event Title', 'type' => 'text', 'required' => true],
                'event_date' => ['label' => 'Event Date', 'type' => 'date', 'nullable' => true],
                'event_time' => ['label' => 'Event Time', 'type' => 'time', 'nullable' => true],
                'location' => ['label' => 'Location', 'type' => 'text', 'nullable' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'nullable' => true],
                'event_image' => ['label' => 'Event Image', 'type' => 'file', 'nullable' => true],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['published' => 'Published', 'unpublished' => 'Unpublished'], 'default' => 'published'],
            ],
        ],
    ],
    'reports' => [
        'student-report' => ['title' => 'Student Report', 'module' => 'students'],
        'room-occupancy-report' => ['title' => 'Room Occupancy Report', 'module' => 'rooms'],
        'fee-due-report' => ['title' => 'Fee Due Report', 'module' => 'fee-payments'],
        'fee-collection-report' => ['title' => 'Fee Collection Report', 'module' => 'fee-payments'],
        'attendance-report' => ['title' => 'Attendance Report', 'module' => 'student-attendance'],
        'visitor-report' => ['title' => 'Visitor Report', 'module' => 'visitors'],
        'complaint-report' => ['title' => 'Complaint Report', 'module' => 'complaints'],
        'leave-report' => ['title' => 'Leave Report', 'module' => 'leaves'],
        'expense-report' => ['title' => 'Expense Report', 'module' => 'expenses'],
        'income-report' => ['title' => 'Income Report', 'module' => 'incomes'],
        'staff-salary-report' => ['title' => 'Staff Salary Report', 'module' => 'staff-payments'],
        'bill-report' => ['title' => 'Bill Report', 'module' => 'bills'],
    ],
];
